# NumPy Fundamentals

## Overview

NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for multidimensional arrays, mathematical operations, linear algebra, random number generation, and various array manipulation techniques.

### Objectives

- Understand NumPy arrays
- Learn array attributes
- Perform indexing and slicing
- Create arrays using different routines
- Apply mathematical operations
- Explore reshaping techniques
- Practice with examples

---

## Topics Covered

1. Introduction to NumPy
2. Creating Arrays
3. Array Attributes
4. Functions of an Array
5. Array Creation Routines
6. Reshaping Arrays
7. Mathematical Operations
8. Practice Examples

---

## Prerequisites

Before running this notebook, install NumPy if it is not already installed.

```python
pip install numpy
```

Import the library using:

```python
import numpy as np
```

# 1. Introduction to NumPy

In this section, we learn how to import the NumPy library, create one-dimensional and multidimensional arrays, and understand the basic properties of arrays.

In [85]:
import numpy as np   #importing numpy library

In [86]:
a= np.array([1,2,3,4,5,6]) #Single dimensional array 1D

In [87]:
print(a) #1D array

[1 2 3 4 5 6]


In [88]:
b= np.array([[1,2,3],[4,5,6]]) #Multiple dimensional arrays

In [89]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
a

array([1, 2, 3, 4, 5, 6])

In [91]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
a.shape #1st attribute

(6,)

In [93]:
b.shape

(2, 3)

In [94]:
a

array([1, 2, 3, 4, 5, 6])

In [95]:
a.size #2nd attribute

6

In [96]:
b.size

6

In [97]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
b.ndim  #number of dimension(ndim) 3rd attribute

2

In [101]:
a.ndim

1

In [102]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
b.T #transpose attribute 4th attribute

array([[1, 4],
       [2, 5],
       [3, 6]])

# 2. Array Attributes

NumPy arrays provide several useful attributes that describe their structure.

The following attributes are covered:

- shape
- size
- ndim
- dtype
- itemsize
- nbytes

These attributes help us understand how NumPy stores and manages data efficiently.

In [104]:
x= np.arange(1,11)  #Range funtion

In [105]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
y= x.reshape(5,2) #Reshape function

In [107]:
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [108]:
a= np.arange(1,7).reshape(2,3)  #Combination of range and reshape function
b= np.arange(7,13).reshape(2,3)

In [109]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [111]:
np. concatenate((a,b)) #Concatelation(we can join two different array)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
np.hstack((a,b)) #Horizontal Stack Concatenation of two different array

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [113]:
np.vstack((a,b)) #Vertical Stack Concatenation

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [114]:
c = np.arange(1,7) #Arange Function

In [115]:
c

array([1, 2, 3, 4, 5, 6])

In [116]:
np.append(c,[7,8,9]) #temprory addition using append at ending of the data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
c=np.append(c,[7,8,9]) #For assigning c permanently using append

In [118]:
c  #Values assigned in c permanently

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.insert(c,0,0) #insertion function at any position

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
c=np.insert(c,0,0) #Permanent insertion

In [121]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.delete(c,[6,7])  #deletion function

array([0, 1, 2, 3, 4, 5, 8, 9])

In [123]:
c=np.delete(c,[6,7])

In [124]:
c #Values assigned in c permanently using delete

array([0, 1, 2, 3, 4, 5, 8, 9])

In [125]:
import numpy as np

arr = np.array([0, 0, 1, 2, 3, 4, 5, 6, 9, 7, 8, 9, 7, 8, 9])

result = arr[np.sort(np.unique(arr, return_index=True)[1])]
print(result)

[0 1 2 3 4 5 6 9 7 8]


# 3. Array Creation Routines

NumPy provides multiple methods for creating arrays.

The following functions are demonstrated:

- zeros()
- ones()
- empty()
- full()
- eye()
- identity()
- arange()
- linspace()

These functions simplify array initialization for different use cases.

In [126]:
np.empty([2,2]) #Creating random data structures using empty

array([[1., 1.],
       [1., 1.]])

In [127]:
np.zeros(5)  #Creating array of zeros

array([0., 0., 0., 0., 0.])

In [128]:
np.zeros([4,4],dtype=int) # array of zeros with int datatype

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [129]:
np.ones(5) #Creating array of ones

array([1., 1., 1., 1., 1.])

In [130]:
np.eye(4) #Concept of identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
np.arange(1,10) #arange funtion is a part of creation routine

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.linspace(0,1,100)
 #this function is similar to arange funtion, in this function stacksize the no. of evenly space value between the interval is specified

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# 4. Array Manipulation

Array manipulation allows us to modify the structure of arrays without changing the original data.

Topics include:

- reshape()
- flatten()
- transpose()
- ravel()
- resize()

These operations are commonly used during data preprocessing.

In [133]:
#Indexing and Slicing in numpy

In [134]:
ar= np.arange(1,11) #ar means array

In [135]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
ar[8]  #value visualize with int 64 bytes / if float the float

np.int64(9)

In [137]:
ar[-7] #Negative Indexing

np.int64(4)

In [138]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
ar[1:8:2] #Slicing [Start:End:Step(take every 2nd element)]

array([2, 4, 6, 8])

In [140]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
ar[1:10:2]

array([ 2,  4,  6,  8, 10])

In [142]:
ar[0:7:-1] #You are asking Python to go backward from index 0 to index 7, which is impossible.So Python returns an empty array

array([], dtype=int64)

In [143]:
ar[7:0:-1] #Reverse a slice (0 to 7)

array([8, 7, 6, 5, 4, 3, 2])

In [144]:
ar[-1:3:-1] # start from last element, move backward, stop before index 3

array([10,  9,  8,  7,  6,  5])

In [145]:
print(type(ar)) #Printing type of data

<class 'numpy.ndarray'>


In [146]:
r=[1,2,3,4,5,6,7,8,9,10]

In [147]:
print(type(r))

<class 'list'>


In [148]:
r

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [149]:
r[0:10:1] #Slicing in 1D array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [188]:
a1=np.arange(1,21).reshape(5,5) # In reshape 5 × 5 = 25 ❌ (needs 25 elements, but only 20 exist)

In [151]:
a1=np.arange(1,21).reshape(4,5) #arange and reshape together

In [152]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [153]:
a1.ndim # to check the no. of dimesion

2

In [154]:
a1[0:1,0:3]

array([[1, 2, 3]])

In [155]:
a1[2:3,0:3]

array([[11, 12, 13]])

In [156]:
a1[3, 2:5]

array([18, 19, 20])

**DATA BROADCASTING** Broadcasting is a way in NumPy that allows arrays of different shapes to perform arithmetic operations together.

In [157]:
import numpy as np

In [158]:
ar= np.arange(1,11) #ar means array

In [159]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
ar[4]=400

In [161]:
ar

array([  1,   2,   3,   4, 400,   6,   7,   8,   9,  10])

In [162]:
ar[5: :1]=500

In [163]:
ar

array([  1,   2,   3,   4, 400, 500, 500, 500, 500, 500])

**FANCY INDEXING** means selecting elements from an array using a list (or array) of indices instead of a single index or a simple slice.

In [164]:
x= np.zeros((10,10))

In [165]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [166]:
print(type(x))

<class 'numpy.ndarray'>


In [167]:
length= x.shape[1] #Shaping

In [168]:
length

10

In [169]:
for i in range(length): # Colon: Python uses indentation to define blocks of code.
  x[i] = i

In [170]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [171]:
x[[1,4,7,8]] #fetching multi-dimensional data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

# 5. Mathematical Operations

NumPy provides efficient mathematical operations that can be performed directly on arrays.

Examples include:

- Addition
- Subtraction
- Multiplication
- Division
- Modulus
- Exponentiation
- Square Root
- Trigonometric Functions
- Aggregate Functions

These operations are optimized for high-performance numerical computation.

**Array selection** means choosing specific elements from an array.

In [172]:
a= list(range(1,11))  #Lists perform operations like repetition and joining.

In [173]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [174]:
a*4  #This does NOT multiply each number by 4 ❌ Instead, for lists, * means repetition.

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [175]:
a+5 #TypeError: can only concatenate list (not "int") to list


TypeError: can only concatenate list (not "int") to list

In [189]:
x= np.arange(1,11)  #Arrays perform mathematical operations element-wise.

In [176]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [177]:
x*4 #An array (NumPy) is used for mathematical operations, so * multiplies each element.

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [24., 24., 24., 24., 24., 24., 24., 24., 24., 24.],
       [28., 28., 28., 28., 28., 28., 28., 28., 28., 28.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.]])

In [178]:
x+5 #Additional operator

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [179]:
x/2 #division operator

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5],
       [4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. ],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [180]:
x>5 #comparison operator

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [181]:
z= np.array(["simran","apple","banana","grapes"])

In [182]:
z

array(['simran', 'apple', 'banana', 'grapes'], dtype='<U6')

In [183]:
z[z=="simran"]

array(['simran'], dtype='<U6')

In [184]:
z[z>="simran"]

array(['simran'], dtype='<U6')

In [185]:
z[z<="simran"]

array(['simran', 'apple', 'banana', 'grapes'], dtype='<U6')

# Summary

In this notebook, we covered the following NumPy concepts:

- Importing NumPy
- Creating One-Dimensional Arrays
- Creating Multi-Dimensional Arrays
- Array Attributes
- Array Functions
- Array Creation Routines
- Array Manipulation
- Mathematical Operations

This notebook serves as a foundation for data analysis and machine learning using Python.